### PR TITLE
Fixed UnicodeEncodeError (print response['title']) and added an exception handler

### PR DESCRIPTION
**Pull request by supersupersnivy97**
Fixed the following error:

print(': {} [{} - {}]'.format(response['title'], response['startDate'], response['endDate']))
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 53-53: Non-BMP character not supported in Tk

by translating everything outside of the BMP to the replacement character.

Also I put

with open(__output_file__, 'w') as f:
         f.write(json.dumps(offers))

at the end of the main instead of inside the loop, so the program doesn't become an I/O bound program.

### CODE REVIEW

**Comment by supersupersnivy97** [comment]
> Fixed the following error:
> 
> print(': {} [{} - {}]'.format(response['title'], response['startDate'], response['endDate']))
> UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 53-53: Non-BMP character not supported in Tk
> 
> by translating everything outside of the BMP to the replacement character.
> 
> Also I put
> 
> with open(**output_file**, 'w') as f:
> f.write(json.dumps(offers))
> 
> at the end of the main instead of inside the loop, so the program doesn't become an I/O bound program.

**Comment by supersupersnivy97** [comment]
avevo chiuso per sbaglio ops

**Comment by giacomoferretti** [comment]
Actually I put the write operation inside the loop so that if the program fails for some reason you wouldn't need to restart the scraper from scratch, but this function has not been implemented yet.

For the UCS-2 encoding problem it seems that it happens only with IDLE and Tk, not in in the console.

**Comment by supersupersnivy97** [comment]
> Actually I put the write operation inside the loop so that if the program fails for some reason you wouldn't need to restart the scraper from scratch, but this function has not been implemented yet.
> 
> For the UCS-2 encoding problem it seems that it happens only with IDLE and Tk, not in in the console.

oh ok (I added an exception handler, see the commit below)

**Pull request merged**
